### ISSUE TITLE
Swipe right app

### ISSUE THREAD

**Issue by Heike-HS** [tanujnotes/olauncher-light#1]
Would prefer the telephone app instead of the dial pad as swipe right app.

Besides that I love both Olauncher and Olauncher light. Thanks!

**Comment by tanujnotes** [comment]
I chose dialer app because in my experience most dialer apps show recently dialed numbers and since most people call same few people again and again, it's convenient. Anyway, ability to change swipe apps will be added at some point. Stay tuned and thank you.
